---
- name: install httpd
  package:
     name: httpd
     state: present
  register: status

- name: configure httpd
  template:
      src: httpd_config.j2
      dest: /etc/httpd/conf.d/my.conf
  when: status.rc == 0
  notify: restart httpd